// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVt2H9HrrY93DjJmIanKSL3R5bx1flYRs',
    appId: '1:320758631780:web:d94b495f4bad7c7893be71',
    messagingSenderId: '320758631780',
    projectId: 'real-estate-management-6a1da',
    authDomain: 'real-estate-management-6a1da.firebaseapp.com',
    storageBucket: 'real-estate-management-6a1da.firebasestorage.app',
    measurementId: 'G-KV5QL5DPEG',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVt2H9HrrY93DjJmIanKSL3R5bx1flYRs',
    appId: '1:320758631780:web:7529bd6f6ed4233493be71',
    messagingSenderId: '320758631780',
    projectId: 'real-estate-management-6a1da',
    authDomain: 'real-estate-management-6a1da.firebaseapp.com',
    storageBucket: 'real-estate-management-6a1da.firebasestorage.app',
    measurementId: 'G-1BDXQJYZC9',
  );
}
